# Generated by Django 3.1.2 on 2020-10-14 02:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Id única de este videojuego para toda la tienda', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('genero', models.CharField(blank=True, choices=[('RPG', 'Juego de rol'), ('Acc', 'Accion'), ('Ave', 'Aventuras'), ('Sbx', 'Mundo abierto'), ('Plt', 'Plataformas'), ('VR', 'Realidad virtual'), ('Ter', 'Terror'), ('BR', 'Battle royale'), ('Otr', 'Otro genero')], default='Otr', help_text='Generos de videojuegos', max_length=3)),
                ('precio', models.IntegerField()),
                ('ESRB', models.CharField(blank=True, choices=[('E', 'Todos'), ('E+10', 'Todos los mayores a 10'), ('T', 'Adolescentes'), ('M', 'Mayores a 17'), ('A', 'Solo adultos'), ('RP', 'Clasificación pendiente')], default='RP', help_text='Clasificacion de edad recomendada para jugar', max_length=4)),
            ],
        ),
    ]
