# Generated by Django 3.1.2 on 2020-10-31 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_videojuego_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videojuego',
            name='descripcion',
        ),
    ]
