# Generated by Django 3.1.2 on 2020-10-31 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_videojuego_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='descripcion',
            field=models.TextField(blank=True, default='', max_length=1000),
        ),
    ]
