# Generated by Django 3.1.2 on 2020-10-31 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_videojuego_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojuego',
            name='imagen',
            field=models.ImageField(default='vdgi/noimage.png', upload_to='vdgi'),
        ),
    ]
