# Generated by Django 3.1.2 on 2020-11-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20201031_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='imagen',
            field=models.ImageField(blank=True, default='/locallibreria/catalog/media/vdgi', null=True, upload_to='media/vdgi/'),
        ),
    ]
