# Generated by Django 3.1.2 on 2020-11-01 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20201031_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='imagen',
            field=models.ImageField(blank=True, default='catalog/media/vdgi/noimage.png', null=True, upload_to='catalog/media/vdgi/'),
        ),
    ]
