# Generated by Django 3.1.2 on 2020-11-01 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20201031_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videojuego',
            name='imagen',
            field=models.ImageField(blank=True, default='media/vdgi/noimage.png', null=True, upload_to='media/vdgi'),
        ),
    ]
